services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wavestore-website-dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./eslint.config.js:/app/eslint.config.js
      - /app/node_modules
    environment:
      - NODE_ENV=development
