export const TEST_INFO_FEATURED = [
  {
    id: 1,
    id_brand: 2,
    id_category: 2,
    item_ID: "ThumbBO5BR",
    img: "/img/items/bass/warwick/ThumbBO5BR/ThumbBO5BR-1.webp",
    title: "Warwick Pro Series Thumb BO 5",
    model:
      "5-string Electric Bass with Ovangkol Body and Neck, Wenge Fingerboard, 2 Active J-style Stacked-coil Pickups, and 2-band EQ/Preamp - Natural Transparent Satin",
    price: "3780.00",
    in_stock: true,
    description: "",
    product_info: "",
    created_at: "",
    updated_at: "",
  },
  {
    id: 2,
    id_brand: 2,
    id_category: 2,
    item_ID: "RS525SC-ABG",
    img: "/img/items/drums/pearl/RS525SC-ABG/RS525SC-ABG-1.webp",
    title: "Pearl RS525SC/C Roadshow",
    model:
      '5-piece Poplar Drum Set with 10" and 12" Toms, 16" Floor Tom, 22" Bass Drum, 14" Snare, Hardware, and 2-piece Cymbal Pack - Aqua Blue Glitter',
    price: "730.00",
    in_stock: true,
    description: "",
    product_info: "",
    created_at: "",
    updated_at: "",
  },
  {
    id: 3,
    id_brand: 2,
    id_category: 2,
    item_ID: "StroboClipHD",
    img: "/img/items/accesories/tuner/StroboClipHD/StroboClipHD-1.webp",
    title: "Peterson StroboClip HD",
    model: "The Peterson StroboClip HD LCD strobe tuner delivers that renowned precision (to a tenth of a cent) in a handy, small clip-on tuner with a detailed backlit display.",
    price: "59.99",
    in_stock: true,
    description: "",
    product_info: "",
    created_at: "",
    updated_at: "",
  },
];
